const currencyTable = [
    { currency : "Euro" ,shortCut: "EUR"},
    { currency : "Afghan afghani" ,shortCut: "AFN"},
    { currency : "Albanian lek" ,shortCut: "ALL"},
    { currency : "Algerian dinar" ,shortCut: "DZD"},
    { currency : "Angolan kwanza" ,shortCut: "AOA"},
    { currency : "East Caribbean dollar" ,shortCut: "XCD"},
    { currency : "Argentine peso" ,shortCut: "ARS"},
    { currency : "Armenian dram" ,shortCut: "AMD"},
    { currency : "Australian dollar" ,shortCut: "AUD"},
    { currency : "Azerbaijani manat" ,shortCut: "AZN"},
    { currency : "Bahamian dollar" ,shortCut: "BSD"},
    { currency : "Bahraini dinar" ,shortCut: "BHD"},
    { currency : "Bangladeshi taka" ,shortCut: "BDT"},
    { currency : "Barbadian dollar" ,shortCut: "BBD"},
    { currency : "Belarusian ruble" ,shortCut: "BYN"},
    { currency : "Belize dollar" ,shortCut: "BZD"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Bhutanese ngultrum" ,shortCut: "BTN"},
    { currency : "Bolivian boliviano" ,shortCut: "BOB"},
    { currency : "Bosnia and Herzegovina convertible mark" ,shortCut: "BAM"},
    { currency : "Botswana pula" ,shortCut: "BWP"},
    { currency : "Brazilian real" ,shortCut: "BRL"},
    { currency : "Brunei dollar" ,shortCut: "BND"},
    { currency : "Bulgarian lev" ,shortCut: "BGN"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Burundian franc" ,shortCut: "BIF"},
    { currency : "Cambodian riel" ,shortCut: "KHR"},
    { currency : "Central African CFA franc" ,shortCut: "XAF"},
    { currency : "Canadian dollar" ,shortCut: "CAD"},
    { currency : "Cape Verdean escudo" ,shortCut: "CVE"},
    { currency : "Chilean peso" ,shortCut: "CLP"},
    { currency : "Chinese yuan" ,shortCut: "CNY"},
    { currency : "Colombian peso" ,shortCut: "COP"},
    { currency : "Comorian franc" ,shortCut: "KMF"},
    { currency : "Costa Rican colón" ,shortCut: "CRC"},
    { currency : "Croatian kuna" ,shortCut: "HRK"},
    { currency : "Cuban peso" ,shortCut: "CUP"},
    { currency : "Czech koruna" ,shortCut: "CZK"},
    { currency : "Congolese franc" ,shortCut: "CDF"},
    { currency : "Danish krone" ,shortCut: "DKK"},
    { currency : "Djiboutian franc" ,shortCut: "DJF"},
    { currency : "East Caribbean dollar" ,shortCut: "XCD"},
    { currency : "Dominican peso" ,shortCut: "DOP"},
    { currency : "United States dollar" ,shortCut: "USD"},
    { currency : "" ,shortCut: ""},
    { currency : "Egyptian pound" ,shortCut: "EGP"},
    { currency : "Central African CFA franc" ,shortCut: "XAF"},
    { currency : "Eritrean nakfa" ,shortCut: "ERN"},
    { currency : "Swazi lilangeni" ,shortCut: "SZL"},
    { currency : "Ethiopian birr" ,shortCut: "ETB"},
    { currency : "Fijian dollar" ,shortCut: "FJD"},
    { currency : "Central African CFA franc" ,shortCut: "XAF"},
    { currency : "Gambian dalasi" ,shortCut: "GMD"},
    { currency : "Georgian lari" ,shortCut: "GEL"},
    { currency : "Ghanaian cedi" ,shortCut: "GHS"},
    { currency : "East Caribbean dollar" ,shortCut: "XCD"},
    { currency : "Guatemalan quetzal" ,shortCut: "GTQ"},
    { currency : "Guinean franc" ,shortCut: "GNF"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Guyanese dollar" ,shortCut: "GYD"},
    { currency : "Haitian gourde" ,shortCut: "HTG"},
    { currency : "Honduran lempira" ,shortCut: "HNL"},
    { currency : "Hungarian forint" ,shortCut: "HUF"},
    { currency : "Icelandic króna" ,shortCut: "ISK"},
    { currency : "Indian rupee" ,shortCut: "INR"},
    { currency : "Indonesian rupiah" ,shortCut: "IDR"},
    { currency : "Iranian rial" ,shortCut: "IRR"},
    { currency : "Iraqi dinar" ,shortCut: "IQD"},
    { currency : "Israeli new shekel" ,shortCut: "ILS"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Jamaican dollar" ,shortCut: "JMD"},
    { currency : "Japanese yen" ,shortCut: "JPY"},
    { currency : "Jordanian dinar" ,shortCut: "JOD"},
    { currency : "Kazakhstani tenge" ,shortCut: "KZT"},
    { currency : "Kenyan shilling" ,shortCut: "KES"},
    { currency : "Australian dollar" ,shortCut: "AUD"},
    { currency : "North Korean won" ,shortCut: "KPW"},
    { currency : "South Korean won" ,shortCut: "KRW"},
    { currency : "Kuwaiti dinar" ,shortCut: "KWD"},
    { currency : "Kyrgyzstani som" ,shortCut: "KGS"},
    { currency : "Lao kip" ,shortCut: "LAK"},
    { currency : "Lebanese pound" ,shortCut: "LBP"},
    { currency : "Lesotho loti" ,shortCut: "LSL"},
    { currency : "Liberian dollar" ,shortCut: "LRD"},
    { currency : "Libyan dinar" ,shortCut: "LYD"},
    { currency : "" ,shortCut: ""},
    { currency : "Swiss franc" ,shortCut: "CHF"},
    { currency : "Malagasy ariary" ,shortCut: "MGA"},
    { currency : "Malawian kwacha" ,shortCut: "MWK"},
    { currency : "Malaysian ringgit" ,shortCut: "MYR"},
    { currency : "Maldivian rufiyaa" ,shortCut: "MVR"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Mauritanian ouguiya" ,shortCut: "MRO"},
    { currency : "Mauritian rupee" ,shortCut: "MUR"},
    { currency : "Mexican peso" ,shortCut: "MXN"},
    { currency : "Moldovan leu" ,shortCut: "MDL"},
    { currency : "Mongolian tögrög" ,shortCut: "MNT"},
    { currency : "Moroccan dirham" ,shortCut: "MAD"},
    { currency : "Mozambican metical" ,shortCut: "MZN"},
    { currency : "Burmese kyat" ,shortCut: "MMK"},
    { currency : "Namibian dollar" ,shortCut: "NAD"},
    { currency : "Australian dollar" ,shortCut: "AUD"},
    { currency : "Nepalese rupee" ,shortCut: "NPR"},
    { currency : "New Zealand dollar" ,shortCut: "NZD"},
    { currency : "Nicaraguan córdoba" ,shortCut: "NIO"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Nigerian naira" ,shortCut: "NGN"},
    { currency : "Macedonian denar" ,shortCut: "MKD"},
    { currency : "Norwegian krone" ,shortCut: "NOK"},
    { currency : "Omani rial" ,shortCut: "OMR"},
    { currency : "Pakistani rupee" ,shortCut: "PKR"},
    { currency : "Israeli new shekel" ,shortCut: "ILS"},
    { currency : "Panamanian balboa" ,shortCut: "PAB"},
    { currency : "Papua New Guinean kina" ,shortCut: "PGK"},
    { currency : "Paraguayan guaraní" ,shortCut: "PYG"},
    { currency : "Peruvian sol" ,shortCut: "PEN"},
    { currency : "Philippine peso" ,shortCut: "PHP"},
    { currency : "Polish zloty" ,shortCut: "PLN"},
    { currency : "Qatari riyal" ,shortCut: "QAR"},
    { currency : "Central African CFA franc" ,shortCut: "XAF"},
    { currency : "Romanian leu" ,shortCut: "RON"},
    { currency : "Russian ruble" ,shortCut: "RUB"},
    { currency : "Rwandan franc" ,shortCut: "RWF"},
    { currency : "East Caribbean dollar" ,shortCut: "XCD"},
    { currency : "East Caribbean dollar" ,shortCut: "XCD"},
    { currency : "East Caribbean dollar" ,shortCut: "XCD"},
    { currency : "" ,shortCut: ""},
    { currency : "Samoan tala" ,shortCut: "WST"},
    { currency : "São Tomé and Príncipe dobra" ,shortCut: "STD"},
    { currency : "Saudi riyal" ,shortCut: "SAR"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Serbian dinar" ,shortCut: "RSD"},
    { currency : "Seychellois rupee" ,shortCut: "SCR"},
    { currency : "Sierra Leonean leone" ,shortCut: "SLL"},
    { currency : "Singapore dollar" ,shortCut: "SGD"},
    { currency : "Solomon Islands dollar" ,shortCut: "SBD"},
    { currency : "Somali shilling" ,shortCut: "SOS"},
    { currency : "South African rand" ,shortCut: "ZAR"},
    { currency : "South Sudanese pound" ,shortCut: "SSP"},
    { currency : "Sri Lankan rupee" ,shortCut: "LKR"},
    { currency : "Sudanese pound" ,shortCut: "SDG"},
    { currency : "Surinamese dollar" ,shortCut: "SRD"},
    { currency : "Swedish krona" ,shortCut: "SEK"},
    { currency : "Swiss franc" ,shortCut: "CHF"},
    { currency : "Syrian pound" ,shortCut: "SYP"},
    { currency : "New Taiwan dollar" ,shortCut: "TWD"},
    { currency : "Tajikistani somoni" ,shortCut: "TJS"},
    { currency : "Tanzanian shilling" ,shortCut: "TZS"},
    { currency : "Thai baht" ,shortCut: "THB"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Tongan pa'anga" ,shortCut: "TOP"},
    { currency : "Trinidad and Tobago dollar" ,shortCut: "TTD"},
    { currency : "Tunisian dinar" ,shortCut: "TND"},
    { currency : "Turkish lira" ,shortCut: "TRY"},
    { currency : "Turkmenistan manat" ,shortCut: "TMT"},
    { currency : "Australian dollar" ,shortCut: "AUD"},
    { currency : "Ugandan shilling" ,shortCut: "UGX"},
    { currency : "Ukrainian hryvnia" ,shortCut: "UAH"},
    { currency : "United Arab Emirates dirham" ,shortCut: "AED"},
    { currency : "British pound" ,shortCut: "GBP"},
    { currency : "Uruguayan peso" ,shortCut: "UYU"},
    { currency : "Uzbekistani som" ,shortCut: "UZS"},
    { currency : "Vanuatu vatu" ,shortCut: "VUV"},
    { currency : "Venezuelan bolívar" ,shortCut: "VEF"},
    { currency : "Vietnamese dong" ,shortCut: "VND"},
    { currency : "Yemeni rial" ,shortCut: "YER"},
    { currency : "Zambian kwacha" ,shortCut: "ZMW"},
]

export default currencyTable