const currencyTable = [
    { currency : "Euro" ,shortCut: "EUR"},
    { currency : "Australian dollar" ,shortCut: "AUD"},
    { currency : "Brazilian real" ,shortCut: "BRL"},
    { currency : "Canadian dollar" ,shortCut: "CAD"},
    { currency : "Chinese yuan" ,shortCut: "CNY"},
    { currency : "Croatian kuna" ,shortCut: "HRK"},
    { currency : "Czech koruna" ,shortCut: "CZK"},
    { currency : "Danish krone" ,shortCut: "DKK"},
    { currency : "United States dollar" ,shortCut: "USD"},
    { currency : "East Caribbean dollar" ,shortCut: "XCD"},
    { currency : "Guatemalan quetzal" ,shortCut: "GTQ"},
    { currency : "Guinean franc" ,shortCut: "GNF"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Guyanese dollar" ,shortCut: "GYD"},
    { currency : "Haitian gourde" ,shortCut: "HTG"},
    { currency : "Honduran lempira" ,shortCut: "HNL"},
    { currency : "Hungarian forint" ,shortCut: "HUF"},
    { currency : "Icelandic króna" ,shortCut: "ISK"},
    { currency : "Indian rupee" ,shortCut: "INR"},
    { currency : "Indonesian rupiah" ,shortCut: "IDR"},
    { currency : "Iranian rial" ,shortCut: "IRR"},
    { currency : "Iraqi dinar" ,shortCut: "IQD"},
    { currency : "Israeli new shekel" ,shortCut: "ILS"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Jamaican dollar" ,shortCut: "JMD"},
    { currency : "Japanese yen" ,shortCut: "JPY"},
    { currency : "Jordanian dinar" ,shortCut: "JOD"},
    { currency : "South Korean won" ,shortCut: "KRW"},
    { currency : "Lao kip" ,shortCut: "LAK"},
    { currency : "Lebanese pound" ,shortCut: "LBP"},
    { currency : "Lesotho loti" ,shortCut: "LSL"},
    { currency : "Liberian dollar" ,shortCut: "LRD"},
    { currency : "Libyan dinar" ,shortCut: "LYD"},
    { currency : "" ,shortCut: ""},
    { currency : "Swiss franc" ,shortCut: "CHF"},
    { currency : "Malagasy ariary" ,shortCut: "MGA"},
    { currency : "Malawian kwacha" ,shortCut: "MWK"},
    { currency : "Malaysian ringgit" ,shortCut: "MYR"},
    { currency : "Maldivian rufiyaa" ,shortCut: "MVR"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Mauritanian ouguiya" ,shortCut: "MRO"},
    { currency : "Mauritian rupee" ,shortCut: "MUR"},
    { currency : "Mexican peso" ,shortCut: "MXN"},
    { currency : "Moldovan leu" ,shortCut: "MDL"},
    { currency : "Mongolian tögrög" ,shortCut: "MNT"},
    { currency : "Moroccan dirham" ,shortCut: "MAD"},
    { currency : "Mozambican metical" ,shortCut: "MZN"},
    { currency : "Burmese kyat" ,shortCut: "MMK"},
    { currency : "Namibian dollar" ,shortCut: "NAD"},
    { currency : "Australian dollar" ,shortCut: "AUD"},
    { currency : "New Zealand dollar" ,shortCut: "NZD"},
    { currency : "Norwegian krone" ,shortCut: "NOK"},
    { currency : "Israeli new shekel" ,shortCut: "ILS"},
    { currency : "Philippine peso" ,shortCut: "PHP"},
    { currency : "Polish zloty" ,shortCut: "PLN"},
    { currency : "Romanian leu" ,shortCut: "RON"},
    { currency : "Russian ruble" ,shortCut: "RUB"},
    { currency : "Samoan tala" ,shortCut: "WST"},
    { currency : "São Tomé and Príncipe dobra" ,shortCut: "STD"},
    { currency : "Saudi riyal" ,shortCut: "SAR"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Serbian dinar" ,shortCut: "RSD"},
    { currency : "Seychellois rupee" ,shortCut: "SCR"},
    { currency : "Sierra Leonean leone" ,shortCut: "SLL"},
    { currency : "Singapore dollar" ,shortCut: "SGD"},
    { currency : "Solomon Islands dollar" ,shortCut: "SBD"},
    { currency : "Somali shilling" ,shortCut: "SOS"},
    { currency : "South African rand" ,shortCut: "ZAR"},
    { currency : "South Sudanese pound" ,shortCut: "SSP"},
    { currency : "Sri Lankan rupee" ,shortCut: "LKR"},
    { currency : "Sudanese pound" ,shortCut: "SDG"},
    { currency : "Surinamese dollar" ,shortCut: "SRD"},
    { currency : "Swedish krona" ,shortCut: "SEK"},
    { currency : "Swiss franc" ,shortCut: "CHF"},
    { currency : "Syrian pound" ,shortCut: "SYP"},
    { currency : "New Taiwan dollar" ,shortCut: "TWD"},
    { currency : "Tajikistani somoni" ,shortCut: "TJS"},
    { currency : "Tanzanian shilling" ,shortCut: "TZS"},
    { currency : "Thai baht" ,shortCut: "THB"},
    { currency : "West African CFA franc" ,shortCut: "XOF"},
    { currency : "Tongan pa'anga" ,shortCut: "TOP"},
    { currency : "Trinidad and Tobago dollar" ,shortCut: "TTD"},
    { currency : "Tunisian dinar" ,shortCut: "TND"},
    { currency : "Turkish lira" ,shortCut: "TRY"},
    { currency : "Turkmenistan manat" ,shortCut: "TMT"},
    { currency : "Australian dollar" ,shortCut: "AUD"},
    { currency : "Ugandan shilling" ,shortCut: "UGX"},
    { currency : "Ukrainian hryvnia" ,shortCut: "UAH"},
    { currency : "United Arab Emirates dirham" ,shortCut: "AED"},
    { currency : "British pound" ,shortCut: "GBP"},
    { currency : "Uruguayan peso" ,shortCut: "UYU"},
    { currency : "Uzbekistani som" ,shortCut: "UZS"},
    { currency : "Vanuatu vatu" ,shortCut: "VUV"},
    { currency : "Venezuelan bolívar" ,shortCut: "VEF"},
    { currency : "Vietnamese dong" ,shortCut: "VND"},
    { currency : "Yemeni rial" ,shortCut: "YER"},
    { currency : "Zambian kwacha" ,shortCut: "ZMW"},
]

export default currencyTable